const GeneralConstants = {
	REMOVE_INSTRUCTOR_TITLE: "Remove Instructor",
	REMOVE_INSTRUCTOR_MESSAGE: "Are you sure you want to remove this instructor? They will not be able to view this page anymore.",
	REMOVE_LESSON_TITLE: "Remove Lesson",
	REMOVE_LESSON_MESSAGE: "Are you sure you want to remove this lesson?",
	REMOVE_STUDENT_TITLE: "Remove Student",
	REMOVE_STUDENT_MESSAGE: "Are you sure you want to remove this student?",
	DELETE_LESSON_TITLE: "Delete Lesson",
	DELETE_LESSON_MESSAGE: "Are you sure you want to delete this lesson?\n This action cannot be undone.",
	CANNOT_REMOVE_INSTRUCTOR_MESSAGE: "There must be at least one instructor teaching a course.",
	CANNOT_DELETE_STEP_TOOLTIP: "There must be at least one step in a lesson!",
	SUCCESSFUL_PUBLISH_LESSON_TITLE: "Lesson Successfully Published",
	SUCCESSFUL_PUBLISH_LESSON_MESSAGE: "Lesson has been successfully published to the your organization!",
	SUCCESSFUL_COMPLETE_LESSON_TITLE: "Lesson Successfully Completed!",
	SUCCESSFUL_COMPLETE_LESSON_MESSAGE: "Lesson has been successfully completed! Close to navigate back to student dashboard",
	ADD_STUDENT_TITLE: "Add Student to Course",
	ADD_INSTRUCTOR_TITLE: "Add Instructor",
	ADD_LESSON_TITLE: "Add Lesson to Course",
	STUDENT: "STUDENT",
	INSTRUCTOR: "INSTRUCTOR",
	ORGANIZATION: "ORGANIZATION",
	NO_ROLE: "ROLE INDEPENDENT",
};

export default GeneralConstants;