const GeneralConstants = {
	REMOVE_INSTRUCTOR_TITLE: 'Remove Instructor',
	REMOVE_INSTRUCTOR_MESSAGE:
		'Are you sure you want to remove this instructor? They will not be able to view this page anymore.',
	REMOVE_LESSON_TITLE: 'Remove Lesson',
	REMOVE_LESSON_MESSAGE: 'Are you sure you want to remove this lesson?',
	REMOVE_STUDENT_TITLE: 'Remove Student',
	REMOVE_STUDENT_MESSAGE: 'Are you sure you want to remove this student?',
	DELETE_LESSON_TITLE: 'Delete Lesson',
	DELETE_LESSON_MESSAGE: 'Are you sure you want to delete this lesson?\n This action cannot be undone.',
	DELETE_COURSE_TITLE: 'Delete Course',
	DELETE_COURSE_MESSAGE: 'Are you sure you want to delete this course? This action cannot be undone.',
	CANNOT_REMOVE_INSTRUCTOR_MESSAGE: 'There must be at least one instructor teaching a course.',
	SUCCESSFUL_PUBLISH_LESSON_MESSAGE: 'Lesson successfully published to your organization!',
	SUCCESSFUL_SAVE_MESSAGE: 'Lesson successfully saved!',
	SUCCESSFUL_DUPLICATE_MESSAGE: 'Lesson successfully duplicated!',
	RESTART_LESSON_TITLE: 'Restart Lesson?',
	RESTART_LESSON_MESSAGE: 'Are you sure you want to restart the lesson?',
	SUCCESSFUL_COMPLETE_LESSON_TITLE: 'Lesson Successfully Completed!',
	SUCCESSFUL_COMPLETE_LESSON_MESSAGE:
		'Lesson has been successfully completed! Close to navigate back to student dashboard',
	CANNOT_PUBLISH_MESSAGE: 'Please make sure all steps are completed before publishing!',
	SAVE_BEFORE_PUBLISH_MESSAGE: 'Please save before publishing!',
	PUBLISH_CONFIRMATION_TITLE: 'Publish Lesson',
	PUBLISH_CONFIRMATION_MESSAGE:
		'Are you sure you want to publish? You cannot edit this lesson after it has been published.',
	UNSAVED_EDITOR_MESSAGE: 'You have unsaved changes, are you sure you want to leave?',
	LEAVE_STUDENT_LESSON_MESSAGE: 'Are you sure you want to leave? This will count as a lesson attempt.',
	ADD_STUDENT_TITLE: 'Add Student to Course',
	ADD_INSTRUCTOR_TITLE: 'Add Instructor',
	ADD_LESSON_TITLE: 'Add Lesson to Course',
	STUDENT: 'STUDENT',
	INSTRUCTOR: 'INSTRUCTOR',
	ORGANIZATION: 'ORGANIZATION',
	NO_ROLE: 'ROLE INDEPENDENT',
	SHOW_PUBLISHED: 'This lesson is already published!\n No changes can be saved.',
	FAILED_SELECTION_MESSAGE: 'Incorrect selection! Try again.',
	POUR_NO_FILL_MESSAGE: 'Cannot pour from empty source tool.',
	STIR_NO_FILL_MESSAGE: 'Cannot stir an empty target tool. ',
	SHAKE_NO_FILL_MESSAGE: 'Cannot shake an empty source tool.',
	BLEND_OVER_FILL_MESSAGE: 'Cannot blend, blender is too full.',
	OVERFLOW_MESSAGE: 'Target source will overflow.',
	LACK_FILL_MESSAGE: 'Not enough fill to complete step.',
	GRIND_NO_FILL_MESSAGE: 'Cannot grind empty source.',
	COFFEE_ERROR_MESSAGE: 'Coffee beans can be poured into a Grinder.'
};

export default GeneralConstants;
